#!/usr/bin/env zsh
#
# dev-up.zsh — bring the whole thing up locally with one command.
#
# Starts a throwaway chain, deploys both contracts to it, writes the resulting
# addresses into web/.env.local, regenerates the ABI bindings, and runs the
# Next.js dev server in the foreground. Ctrl-C stops everything.
#
# Prerequisites: Foundry (forge / cast / anvil) and Node.js 20+.
# By default it starts a FRESH chain, killing any Anvil already running. That
# keeps the deployed addresses deterministic — reusing a chain that already has
# deployments on it shifts the deployer's nonce and moves every address.
#
# Usage:  ./scripts/dev-up.zsh [port]           # default 3000, fresh chain
#         ./scripts/dev-up.zsh 3001 --reuse     # keep an existing chain and its state

set -euo pipefail

readonly RPC="http://127.0.0.1:8545"
# anvil's first development account. Printed in anvil's own banner and public by
# design — it must never be used on a real network.
readonly DEV_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
readonly PORT="${1:-3000}"
readonly REUSE="${2:-}"
readonly ROOT="${0:A:h:h}"  # contracts/tictactoe
readonly REPO="${ROOT:h:h}"  # リポジトリの最上位（Next アプリ）

anvil_pid=""
cleanup() {
  [[ -n "$anvil_pid" ]] && kill "$anvil_pid" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

step() { print -P "\n%F{cyan}▸ $1%f" }

step "Starting a local chain on $RPC"
if [[ "$REUSE" == "--reuse" ]] && cast block-number --rpc-url "$RPC" >/dev/null 2>&1; then
  print "  Reusing the chain already running. Addresses may differ from a fresh run."
else
  if cast block-number --rpc-url "$RPC" >/dev/null 2>&1; then
    print "  Stopping the chain already on $RPC (pass --reuse to keep it)."
    # Kill by port, not by name: `pkill -f anvil` takes down every Anvil on the
    # machine, including ones other worktrees are using, and misses any started
    # by absolute path.
    local pid
    pid=$(lsof -nP -iTCP:8545 -sTCP:LISTEN -t 2>/dev/null) && kill $pid 2>/dev/null || true
    local waited=0
    while cast block-number --rpc-url "$RPC" >/dev/null 2>&1; do
      sleep 0.2
      waited=$((waited + 1))
      (( waited > 50 )) && { print -u2 "Something is still holding $RPC. Stop it and retry."; exit 1 }
    done
  fi
  anvil --silent &
  anvil_pid=$!
  until cast block-number --rpc-url "$RPC" >/dev/null 2>&1; do sleep 0.2; done
  print "  Fresh chain, chain id $(cast chain-id --rpc-url "$RPC")."
fi

step "Deploying the contracts"
cd "$ROOT"
local deploy_log
deploy_log=$(forge script script/Deploy.s.sol \
  --rpc-url "$RPC" --broadcast --private-key "$DEV_KEY" 2>&1)

local pvp solo
pvp=$(print -r -- "$deploy_log" | grep -oE 'NEXT_PUBLIC_TICTACTOE_ADDRESS_31337=0x[0-9a-fA-F]{40}' | tail -1 | cut -d= -f2)
solo=$(print -r -- "$deploy_log" | grep -oE 'NEXT_PUBLIC_SOLO_ADDRESS_31337=0x[0-9a-fA-F]{40}' | tail -1 | cut -d= -f2)

if [[ -z "$pvp" || -z "$solo" ]]; then
  print -u2 "Deployment failed:"
  print -u2 -r -- "$deploy_log"
  exit 1
fi

print "  TicTacToe:     $pvp"
print "  SoloTicTacToe: $solo"

step "Writing web/.env.local"
cat > "$REPO/.env.local" <<ENV
# Generated by scripts/dev-up.zsh. Safe to regenerate; not committed.
NEXT_PUBLIC_SITE_URL=http://localhost:$PORT
NEXT_PUBLIC_TICTACTOE_ADDRESS_31337=$pvp
NEXT_PUBLIC_SOLO_ADDRESS_31337=$solo
ENV

step "Generating ABI bindings from the fresh build"
cd "$REPO"
[[ -d node_modules ]] || npm install
npm run wagmi --silent

print -P "\n%F{green}Ready.%f Open http://localhost:$PORT"
cat <<'NOTES'

  Point MetaMask at the local chain:
    Network name  Anvil
    RPC URL       http://127.0.0.1:8545
    Chain ID      31337
    Currency      ETH

  Import two of anvil's accounts so you can play both sides. Their keys are
  deterministic; the first two are:
    0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
  Each starts with 10,000 test ETH. They are public keys from anvil's banner —
  never use them anywhere real.

  Ctrl-C stops the dev server and the chain.

NOTES

step "Starting Next.js"
# Not `exec`: replacing the shell would discard the EXIT trap, leaving the chain
# running whenever the dev server exits on its own.
npm run dev -- --port "$PORT"
